kowainik/learn4haskell

learn4haskell.cabal
src/Chapter2.hs

[#2] PR 2 tasks

---

learn4haskell.cabal
src/Chapter3.hs

[#3] PR 3 tasks

---

learn4haskell.cabal
src/Chapter4.hs

[#4] PR 4 tasks

---

.github/workflows/ci.yml
learn4haskell.cabal
src/Chapter1.hs
src/Chapter2.hs
src/Chapter3.hs
src/Chapter4.hs
test/DoctestChapter1.hs
test/DoctestChapter2.hs
test/DoctestChapter3.hs
test/DoctestChapter4.hs

[#12] Explore 'doctest' testing for testing GHCi tasks

---

.github/workflows/ci.yml
learn4haskell.cabal
test/Spec.hs
test/Test/Chapter1.hs
test/Test/Chapter2.hs
test/Test/Chapter3.hs
test/Test/Chapter4.hs

Add tests for Chapter 1

---

.github/workflows/ci.yml
src/Chapter2.hs
test/Test/Chapter2.hs

Add tests for Chapter 2

---

.github/workflows/ci.yml
src/Chapter3.hs
src/Chapter4.hs
test/Test/Chapter4.hs

[#6] Add tests for Chapter 4

---

Makefile

[#15] Create Makefile with commands

---

README.md
src/Chapter1.hs
src/Chapter2.hs
src/Chapter3.hs
src/Chapter4.hs

[#5] Main project description

---

README.md
src/Chapter2.hs

[#41] Add newlines to fix doctest for the second chapter

---

src/Chapter1.hs

I think it's worth to differentiate between strong and static typing here

Characterize strong and static typing separately

---

src/Chapter1.hs

Chapter 1 tests passing with trimmed code.
@vrom911 @chshersh

Trim Chapter1, Task 9 reference solution

---

src/Chapter3.hs

Improve some wording in Chapter 3 tasks

---

test/Test/Chapter2.hs

Fix typo in the Test description for task 12*

Update Test of Chapter2.hs

---

README.md

Update Readme with more verbose english

---

Makefile
test/Test/Chapter1.hs
test/Test/Chapter2.hs
test/Test/Chapter4.hs

Add a make command to run all tests

Tests: Improve tests titles

---

test/Test/Chapter1.hs

add test chapter 1 task 7

---

src/Chapter2.hs
src/Chapter3.hs
src/Chapter4.hs

Even more typos

---

src/Chapter2.hs

Chapter 2 fix for lambda description - hope this works this time.

Changed 'append number 3' to 'add number 3'

---

src/Chapter2.hs

Fix typos in chapter 2.

---

test/Test/Chapter1.hs

I think these should be 1st, not trying to include this towards hacktoberfest; just correcting the typo. :)

typos in Chapter1.hs

---

README.md

Resolves #167 
Description: Change the description with more readable content.

Issue: README.md: *boiling #167

---

src/Chapter3.hs

Fix typo in chapter 3

---

src/Chapter3.hs

Fix typo 'MkNight' -> 'MkKnight'

---

.github/workflows/ci.yml

[#336] Use default main branch

---

ARPL @vrom911
README.md
src/Chapter1.hs
src/Chapter2.hs
src/Chapter3.hs
src/Chapter4.hs

Typos Chapters 1, 2, 3 & 4

---

.github/workflows/ci.yml

Update haskell action to prevent errors

---

README.md

fixed verbiage, missing word.

---

.github/workflows/ci.yml
README.md
learn4haskell.cabal

[#389] Update GHC to 8.10.4

---

src/Chapter3.hs

[#430] Chapter 3 knight Monster clarification

---

src/Chapter1.hs

[#529] Fix typo in chapter 1's task 2, replace `Add` with `add`

---

.github/workflows/ci.yml
learn4haskell.cabal

[#558] Upgrade to GHC-9.4
